/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw;

import org.apache.commons.cli.*;

public class App {

    public static void main(String[] args) {

        //create options object
        Options options = new Options();

        //add -h, --help -> prints help/usage message
        options.addOption("h","help",false,"print usage message");
        //add -b <file>, --batch <file> -> processes provided file rather than standard input file
        options.addOption("b", "batch",true,"batch file containing expressions to evaluate");
        //add -o <file>, --output <file> -> sends the output to the provided file and standard output
        options.addOption("o", "output",true,"output file");

        //create the parser
        CommandLineParser parser = new DefaultParser();
        try {
            //parse the command line arguments
            CommandLine cmd = parser.parse(options, args);
            //check for options
            if (cmd.hasOption("h")) {
                //print help/usage message
                HelpFormatter formatter = new HelpFormatter();
                formatter.printHelp("eval", options, true);
            }
            if (cmd.hasOption("b")) {
                //get file name
                System.out.println("Batch value: " + args[0]);
                //process provided file
            }
            if (cmd.hasOption("o")) {
                //get file name
                //send output to provided file and standard output
                System.out.println("Output value: " + args[0]);
            }
        }catch (ParseException exp) {
            //oops, something went wrong
            System.err.println("Parsing failed. Reason: " + exp.getMessage());
        }
    }
}
